version: '3.9'

services:
  frontend:
    image: frontend:latest
    build:
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - 3-tier

    depends_on:
      - backend

  backend:
    image: backend:latest
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    networks:
      - 3-tier
    environment:
      - MONGO_URI=mongodb://database:27017/mydatabase
    depends_on:
      - database

  database:
    image: mongo:6.0
    container_name: database
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - 3-tier
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  3-tier: